### ISSUE TITLE
Unexpected token [

### ISSUE THREAD

**Issue by jacobomendizabal** [ionic-team/ionic-conference-app#403]
Please, I have a issue in ionic-conference-app, I followed the steps of driftyco/ionic-conference-app:

When I run ionic serve show me the next message:

$ ionic serve
C:\Users\AppData\Roaming\npm\node_modules\ionic\dist\index.js:24
        const [xcode, iosDeploy, iosSim,] = yield Promise.all([
              ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Jacobo\AppData\Roaming\npm\node_modules\ionic\bin\ionic:8:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

I would appreciate any help in this regard.

**Comment by brandyscarney** [comment]
Can you run `ionic -v` and `ionic info` please and paste the output here?

**Comment by jlbeard84** [comment]
I just started experiencing this issue as well, on Ionic 3.1.2 after a recent upgrade from another 3.X version. The commands ionic -v and ionic info don't produce any output - they give the same error as described above. I've done all the usual stuff - uninstall -g, clean cache, install -g to no avail.

**Comment by jlbeard84** [comment]
And nevermind - found the fix. I was using an older version of node. Upgraded to latest and everything works now.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
