### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by yonghongqqin** [ionic-team/ionic-conference-app#684]
when i ionic serve, it always has the below exception, any idea:

```
**[ng] i ｢wdm｣: wait until bundle finished: /
[ng] (node:10868) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Projects\ionic\ionic-conference-app\node_modules\_@ionic_core@4.0.0-beta.15@@ionic\package.json'
[ng]     at Object.openSync (fs.js:436:3)
[ng]     at Object.readFileSync (fs.js:341:35)
[ng]     at LicenseExtractor.readPackageJson (C:\Projects\ionic\ionic-conference-app\node_modules\_license-webpack-plugin@1.5.0@license-webpack-plugin\dist\LicenseExtractor.js:126:23)
[ng]     at LicenseExtractor.parsePackage (C:\Projects\ionic\ionic-conference-app\node_modules\_license-webpack-plugin@1.5.0@license-webpack-plugin\dist\LicenseExtractor.js:23:32)
[ng]     at ModuleProcessor.processPackage (C:\Projects\ionic\ionic-conference-app\node_modules\_license-webpack-plugin@1.5.0@license-webpack-plugin\dist\ModuleProcessor.js:44:46)
[ng]     at ModuleProcessor.processFile (C:\Projects\ionic\ionic-conference-app\node_modules\_license-webpack-plugin@1.5.0@license-webpack-plugin\dist\ModuleProcessor.js:41:21)
[ng]     at fileCallback (C:\Projects\ionic\ionic-conference-app\node_modules\_license-webpack-plugin@1.5.0@license-webpack-plugin\dist\LicenseWebpackPlugin.js:107:61)
[ng]     at moduleCallback (C:\Projects\ionic\ionic-conference-app\node_modules\_license-webpack-plugin@1.5.0@license-webpack-plugin\dist\LicenseWebpackPlugin.js:114:21)
[ng]     at C:\Projects\ionic\ionic-conference-app\node_modules\_license-webpack-plugin@1.5.0@license-webpack-plugin\dist\LicenseWebpackPlugin.js:126:29
[ng]     at Array.forEach (<anonymous>)
[ng]     at emitCallback (C:\Projects\ionic\ionic-conference-app\node_modules\_license-webpack-plugin@1.5.0@license-webpack-plugin\dist\LicenseWebpackPlugin.js:92:32)
[ng]     at _err0 (eval at create (C:\Projects\ionic\ionic-conference-app\node_modules\_tapable@1.1.0@tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
[ng]     at callback (C:\Projects\ionic\ionic-conference-app\node_modules\_copy-webpack-plugin@4.6.0@copy-webpack-plugin\dist\index.js:77:17)
[ng]     at C:\Projects\ionic\ionic-conference-app\node_modules\_copy-webpack-plugin@4.6.0@copy-webpack-plugin\dist\index.js:118:24
[ng] (node:10868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
[ng] (node:10868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**
```

**Comment by brandyscarney** [comment]
Did you run `npm install` after cloning the directory?

**Comment by brandyscarney** [comment]
I'm going to close this since there has been no response. If you are having this issue on a newly created Ionic project after using `ionic start`, please create an issue on the [ionic-cli repository](https://github.com/ionic-team/ionic-cli/issues) by filling out the provided template to gather the most information possible.

If you're only seeing this after cloning the conference app, please try running `npm install` like my above comment. Thanks!
